plugins {
    id 'java-library'
}

group = 'com.alphalens'
version = '0.0.1-SNAPSHOT'
description = 'Plug-and-play Spring auth library (JWT cookies, login/register/refresh)'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web:3.4.2'
    api 'org.springframework.boot:spring-boot-starter-validation:3.4.2'
    api 'org.springframework.boot:spring-boot-starter-security:3.4.2'
    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.4.2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.4.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
